import type { AxiosResponse } from 'axios';
import { PolicyPayload, PolicyResponse } from '@/libs/types/policy';

import { API_POLICY_GET } from '@/constants/api.constant';

import baseClient from './api.config';
const MOCK_DATA = [
  {
    // "policy_type": "MOTOR POLICY - PRIVATE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2024-05-21',
    end_date: '2025-05-20',
    issue_date: '2024-05-21',
    plan_type: 'Comprehensive - Family NCD Builder',
    scheme: 'Tailored Workshop',
    intermediary_name: 'AON SINGAPORE (ORG) PTE. LTD.',
    premium: 1000.0,
    policy_status: 'active',
    tags: 'renewed',
    policy_holder: {
      full_name: 'TAN AH KOW',
      marital_status: 'Married',
      mobile_number: '+65 9123 4567',
      email: 'tanak@email.com',
      address: {
        address_line1: '123 YISHUN AVENUE 1',
        address_line2: '#05-123',
        postal_code: '760123',
      },
    },
    drivers: [
      {
        full_name: 'LIM WEI LING',
        is_main_driver: false,
      },
    ],
    vehicle: {
      registration_number: 'SMC3345U@040620',
      chassis_number: 'JM1FDH53A4U049828',
      capacity: '1598 TO 1599 CC',
      vehicle_usage: 'MOTOR PRIVATE CAR',
      make_model: 'TOYOTA COROLLA ALTIS 1.6',
      engine_number: '1N8198751',
      registration_year: 2018,
      hire_purchase_company: 'N/A',
      registration_no: 'SMC3345U@040620',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: 100.0,
        standard_excess: 1000.0,
        standard_excess_outside_sg: 1000.0,
      },
      additional_excess: {
        unnamed_drivers: 500.0,
        young_or_inexperienced: 3000.0,
      },
    },
    policy_no: 'MC2024001',
  },
  {
    // "policy_type": "MOTOR POLICY - MOTORCYCLE",
    policy_type: 'motorcycle',
    policy_type_name: 'moto vehicle - motocycle',
    start_date: '2023-08-05',
    end_date: '2024-08-04',
    issue_date: '2023-08-05',
    plan_type: 'Comprehensive - Motorcycle',
    scheme: 'Authorized Workshop',
    intermediary_name: 'NTUC INCOME (SINGAPORE) PTE. LTD.',
    premium: 400.0,
    policy_status: 'expired',
    tags: null,
    policy_holder: {
      full_name: 'WONG KAH SENG',
      marital_status: 'Single',
      mobile_number: '+65 8234 5678',
      email: 'wongs@email.com',
      address: {
        address_line1: '789 ANG MO KIO AVENUE 5',
        address_line2: '##08-123',
        postal_code: '560789',
      },
    },
    drivers: [],
    vehicle: {
      registration_number: 'SGM9876C',
      chassis_number: 'JM1FDK45A4U801234',
      capacity: '150 CC',
      vehicle_usage: 'MOTOR MOTORCYCLE',
      make_model: 'YAMAHA YZF-R15',
      engine_number: '201987529',
      registration_year: 2015,
      hire_purchase_company: 'N/A',
      registration_no: 'SGM9876C',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: null,
        standard_excess: 500.0,
        standard_excess_outside_sg: 500.0,
      },
      additional_excess: {
        unnamed_drivers: 300.0,
        young_or_inexperienced: 2000.0,
      },
    },
    policy_no: 'MC2023005',
  },
  {
    // "policy_type": "DOMESTIC MAID INSURANCE",
    policy_type: 'maid',
    policy_type_name: 'maid',
    start_date: '2024-06-10',
    end_date: '2025-06-09',
    issue_date: '2023-06-23',
    plan_type: 'Classic',
    scheme: 'ABC World Agency',
    intermediary_name: null,
    premium: 348.9,
    policy_status: 'active',
    tags: null,
    policy_holder: {
      full_name: 'ANNABEL NELSON',
      marital_status: 'Married',
      mobile_number: '+65 8765 4321',
      email: 'annabel@email.com',
      address: {
        address_line1: '20 CLEMENTI ROAD, STREET 13',
        address_line2: '##11-45',
        postal_code: '560749',
      },
    },
    maid_info: {
      id: 'S0289-93L',
      name: 'MARY JANE',
      date_of_birth: '2000-05-13',
      gender: null,
      phone_number: '65197230',
      nationality: 'FILIPINO',
      passport_number: null,
      forgeign_id_number: null,
    },
    policy_no: 'GMA23F0061460',
  },
  {
    // "policy_type": "MOTOR POLICY - PRIVATE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2024-01-15',
    end_date: '2025-01-14',
    issue_date: '2024-01-15',
    plan_type: 'Comprehensive Plus',
    scheme: 'Authorized Workshop',
    intermediary_name: 'MSIG INSURANCE (SINGAPORE) PTE. LTD.',
    premium: 1400.0,
    policy_status: 'active',
    tags: 'pending_renewal',
    policy_holder: {
      full_name: 'NEESHA D/O KRISHNAMOORTHY (NOT DRIVING)',
      marital_status: 'Single',
      mobile_number: '+65 8765 4321',
      email: 'neesha.k@email.com',
      address: {
        address_line1: '547 WOODLANDS DRIVE 16',
        address_line2: '#06-123',
        postal_code: '730547',
      },
    },
    drivers: [
      {
        full_name: 'PRIYA D/O KRISHNAMOORTHY',
        is_main_driver: false,
      },
    ],
    vehicle: {
      registration_number: 'SJR5319D',
      chassis_number: 'JM1FNH35A4U004929',
      capacity: '1499 CC',
      vehicle_usage: 'MOTOR PRIVATE CAR',
      make_model: 'MITSUBISHI LANCER 1.6',
      engine_number: '1N8198579',
      registration_year: 2012,
      hire_purchase_company: 'FWA CAPITAL PTE LTD',
      registration_no: 'SJR5319D',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: 100.0,
        standard_excess: 1000.0,
        standard_excess_outside_sg: 1000.0,
      },
      additional_excess: {
        unnamed_drivers: 500.0,
        young_or_inexperienced: 3000.0,
      },
    },
    policy_no: 'MC2024002',
  },
  {
    // "policy_type": "MOTOR POLICY - PRIVATE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2024-02-10',
    end_date: '2025-02-09',
    issue_date: '2024-02-10',
    plan_type: 'Comprehensive - Standard',
    scheme: 'Authorized Workshop',
    intermediary_name: 'NTUC INCOME (SINGAPORE) PTE. LTD.',
    premium: 1000.0,
    policy_status: 'active',
    tags: 'pending_renewal',
    policy_holder: {
      full_name: 'LIM WEI LING',
      marital_status: 'Married',
      mobile_number: '+65 9234 5678',
      email: 'limwl@email.com',
      address: {
        address_line1: '456 ANG MO KIO NORTH STREET 3',
        address_line2: '#12-456',
        postal_code: '560456',
      },
    },
    vehicle: {
      registration_number: 'SGY2345D',
      chassis_number: 'JM1FDK45A4U801234',
      capacity: '1500 TO 1599 CC',
      vehicle_usage: 'MOTOR PRIVATE CAR',
      make_model: 'HONDA CIVIC 1.6',
      engine_number: '4019835A',
      registration_year: 2012,
      hire_purchase_company: 'N/A',
      registration_no: 'SGY2345D',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: 100.0,
        standard_excess: 1000.0,
        standard_excess_outside_sg: 1000.0,
      },
      additional_excess: {
        unnamed_drivers: 500.0,
        young_or_inexperienced: 3000.0,
      },
    },
    policy_no: 'MC2024006',
  },
  {
    // "policy_type": "DOMESTIC MAID INSURANCE",
    policy_type: 'maid',
    policy_type_name: 'maid',
    start_date: '2024-02-15',
    end_date: '2025-02-14',
    issue_date: '2024-02-15',
    plan_type: 'Classic',
    scheme: 'Direct Sales',
    intermediary_name: null,
    premium: 348.9,
    policy_status: 'active',
    tags: 'policy renewed',
    policy_holder: {
      full_name: 'ANNABEL NELSON',
      marital_status: 'Married',
      mobile_number: '+65 8765 4321',
      email: 'annabel@email.com',
      address: {
        address_line1: '20 CLEMENTI ROAD, STREET 13',
        address_line2: '##11-45',
        postal_code: '560749',
      },
    },
    maid_info: {
      id: 'MZ34537E',
      name: 'SUCI NURULITA',
      date_of_birth: '1998-08-21',
      gender: null,
      phone_number: '196 23550',
      nationality: 'INDONESIA',
      passport_number: null,
      forgeign_id_number: null,
    },
    policy_no: 'GMA23F0061461',
  },
  {
    // "policy_type": "MOTOR POLICY - PRIVATE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2025-03-01',
    end_date: '2026-02-28',
    issue_date: '2025-02-25',
    plan_type: 'Comprehensive - Standard',
    scheme: 'Direct Sales',
    intermediary_name: null,
    premium: 950.0,
    policy_status: 'active',
    tags: null,
    policy_holder: {
      full_name: 'CHUA BENG HUAT',
      marital_status: 'Divorced',
      mobile_number: '+65 9876 5432',
      email: 'chua.bh@webmail.sg',
      address: {
        address_line1: 'BLK 34 TAMPINES STREET 91',
        address_line2: '#10-205',
        postal_code: '520034',
      },
    },
    drivers: [],
    vehicle: {
      registration_number: 'SJQ1234F',
      chassis_number: 'JM1FDK45A4U908765',
      capacity: '1998 CC',
      vehicle_usage: 'MOTOR PRIVATE CAR',
      make_model: 'TOYOTA CAMRY 2.0',
      engine_number: '1N1234567',
      registration_year: 2020,
      hire_purchase_company: 'N/A',
      registration_no: 'SJQ1234F',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: 100.0,
        standard_excess: 1000.0,
        standard_excess_outside_sg: 1000.0,
      },
      additional_excess: {
        unnamed_drivers: 500.0,
        young_or_inexperienced: 3000.0,
      },
    },
    policy_no: 'MC2025010',
  },
  {
    // "policy_type": "DOMESTIC MAID INSURANCE",
    policy_type: 'maid',
    policy_type_name: 'maid',
    start_date: '2025-01-01',
    end_date: '2025-12-31',
    issue_date: '2024-12-28',
    plan_type: 'Premium',
    scheme: 'Standard Agency',
    intermediary_name: 'ACE INSURANCE PTE LTD',
    premium: 450.5,
    policy_status: 'active',
    tags: null,
    policy_holder: {
      full_name: 'MARK GOH',
      marital_status: 'Married',
      mobile_number: '+65 8234 1122',
      email: 'mark.goh@corp.com',
      address: {
        address_line1: '1 RAFFLES PLACE',
        address_line2: '#35-01',
        postal_code: '048616',
      },
    },
    maid_info: {
      id: 'M0123-01D',
      name: 'AIDA BINTI ROSLAN',
      date_of_birth: '1990-09-05',
      gender: 'Female',
      phone_number: '56781234',
      nationality: 'MALAYSIAN',
      passport_number: null,
      forgeign_id_number: null,
    },
    policy_no: 'GMA24F0071120',
  },
  {
    // "policy_type": "MOTOR POLICY - PRIVATE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2023-10-10',
    end_date: '2024-10-09',
    issue_date: '2023-10-01',
    plan_type: 'Comprehensive Plus',
    scheme: 'Authorized Workshop',
    intermediary_name: 'AON SINGAPORE (ORG) PTE. LTD.',
    premium: 1550.0,
    policy_status: 'expired',
    tags: null,
    policy_holder: {
      full_name: 'TAN SU YEAN',
      marital_status: 'Single',
      mobile_number: '+65 9100 2000',
      email: 't.suyean@gmail.com',
      address: {
        address_line1: 'BLK 200 HOUGANG AVENUE 5',
        address_line2: '#15-300',
        postal_code: '530200',
      },
    },
    drivers: [],
    vehicle: {
      registration_number: 'SLK8888H',
      chassis_number: 'JM1FNH35A4U999999',
      capacity: '2496 CC',
      vehicle_usage: 'MOTOR PRIVATE CAR',
      make_model: 'MERCEDES-BENZ E250',
      engine_number: '900012345',
      registration_year: 2017,
      hire_purchase_company: 'N/A',
      registration_no: 'SLK8888H',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: 200.0,
        standard_excess: 1500.0,
        standard_excess_outside_sg: 1500.0,
      },
      additional_excess: {
        unnamed_drivers: 500.0,
        young_or_inexperienced: 3000.0,
      },
    },
    policy_no: 'MC2023007',
  },
  {
    // "policy_type": "MOTOR POLICY - PRIVATE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2025-06-05',
    end_date: '2026-06-04',
    issue_date: '2025-06-01',
    plan_type: 'Comprehensive - Standard',
    scheme: 'Tailored Workshop',
    intermediary_name: 'NTUC INCOME (SINGAPORE) PTE. LTD.',
    premium: 850.0,
    policy_status: 'active',
    tags: 'renewed',
    policy_holder: {
      full_name: 'RACHEL LIM',
      marital_status: 'Married',
      mobile_number: '+65 8333 4444',
      email: 'rachel.lim@work.com',
      address: {
        address_line1: '10 BEDOK ROAD',
        address_line2: '#01-02',
        postal_code: '469351',
      },
    },
    drivers: [
      {
        full_name: 'ALAN WONG',
        is_main_driver: false,
      },
    ],
    vehicle: {
      registration_number: 'SJX7777J',
      chassis_number: 'JM1FNH35A4U112233',
      capacity: '1799 CC',
      vehicle_usage: 'MOTOR PRIVATE CAR',
      make_model: 'SUBARU IMPREZA 1.8',
      engine_number: '4019855C',
      registration_year: 2019,
      hire_purchase_company: 'N/A',
      registration_no: 'SJX7777J',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: 100.0,
        standard_excess: 1000.0,
        standard_excess_outside_sg: 1000.0,
      },
      additional_excess: {
        unnamed_drivers: 500.0,
        young_or_inexperienced: 3000.0,
      },
    },
    policy_no: 'MC2025011',
  },
  {
    // "policy_type": "DOMESTIC MAID INSURANCE",
    policy_type: 'maid',
    policy_type_name: 'maid',
    start_date: '2025-03-10',
    end_date: '2026-03-09',
    issue_date: '2025-03-05',
    plan_type: 'Classic',
    scheme: 'Online Direct',
    intermediary_name: null,
    premium: 310.0,
    policy_status: 'active',
    tags: 'new policy',
    policy_holder: {
      full_name: 'GARY CHIA',
      marital_status: 'Single',
      mobile_number: '+65 9111 2222',
      email: 'gary.chia@test.net',
      address: {
        address_line1: '21 CLEMENTI DRIVE',
        address_line2: '#05-09',
        postal_code: '129845',
      },
    },
    maid_info: {
      id: 'S0500-11A',
      name: 'KHIN MYO SAN',
      date_of_birth: '1985-12-15',
      gender: 'Female',
      phone_number: '88887777',
      nationality: 'MYANMAR',
      passport_number: null,
      forgeign_id_number: null,
    },
    policy_no: 'GMA25F0080001',
  },
  {
    // "policy_type": "MOTOR POLICY - MOTORCYCLE",
    policy_type: 'motorcycle',
    policy_type_name: 'motor vehicle - motorcycle',
    start_date: '2024-09-20',
    end_date: '2025-09-19',
    issue_date: '2024-09-15',
    plan_type: 'Third Party Only',
    scheme: 'Direct Sales',
    intermediary_name: null,
    premium: 250.0,
    policy_status: 'active',
    tags: null,
    policy_holder: {
      full_name: 'PETER NG',
      marital_status: 'Married',
      mobile_number: '+65 9765 4321',
      email: 'peter.ng@home.sg',
      address: {
        address_line1: 'BLK 500 YISHUN AVENUE 11',
        address_line2: '#03-100',
        postal_code: '760500',
      },
    },
    drivers: [],
    vehicle: {
      registration_number: 'FBM5432B',
      chassis_number: 'JM1FDH53A4U000001',
      capacity: '500 CC',
      vehicle_usage: 'MOTOR MOTORCYCLE',
      make_model: 'HONDA CB500X',
      engine_number: '1N9876543',
      registration_year: 2021,
      hire_purchase_company: 'N/A',
      registration_no: 'FBM5432B',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: null,
        standard_excess: 500.0,
        standard_excess_outside_sg: 500.0,
      },
      additional_excess: {
        unnamed_drivers: 300.0,
        young_or_inexperienced: 2000.0,
      },
    },
    policy_no: 'MC2024009',
  },
  {
    // "policy_type": "MOTOR POLICY - PRIVATE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2025-01-01',
    end_date: '2025-12-31',
    issue_date: '2024-12-20',
    plan_type: 'Comprehensive - Standard',
    scheme: 'Authorized Workshop',
    intermediary_name: 'AON SINGAPORE (ORG) PTE. LTD.',
    premium: 1250.0,
    policy_status: 'active',
    tags: 'policy renewed',
    policy_holder: {
      full_name: 'SHARON CHIA',
      marital_status: 'Divorced',
      mobile_number: '+65 9988 7766',
      email: 'sharon.c@singtel.net',
      address: {
        address_line1: '1 ORCHARD ROAD',
        address_line2: '##22-01',
        postal_code: '238823',
      },
    },
    drivers: [],
    vehicle: {
      registration_number: 'SJW1000K',
      chassis_number: 'JM1FNH35A4U987654',
      capacity: '1998 CC',
      vehicle_usage: 'MOTOR PRIVATE CAR',
      make_model: 'MAZDA 6 2.0',
      engine_number: '4019800D',
      registration_year: 2022,
      hire_purchase_company: 'OCBC BANK',
      registration_no: 'SJW1000K',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: 100.0,
        standard_excess: 1000.0,
        standard_excess_outside_sg: 1000.0,
      },
      additional_excess: {
        unnamed_drivers: 500.0,
        young_or_inexperienced: 3000.0,
      },
    },
    policy_no: 'MC2025012',
  },
  {
    // "policy_type": "DOMESTIC MAID INSURANCE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2024-04-05',
    end_date: '2025-04-04',
    issue_date: '2024-03-25',
    plan_type: 'Classic',
    scheme: 'Direct Sales',
    intermediary_name: null,
    premium: 320.0,
    policy_status: 'expired',
    tags: null,
    policy_holder: {
      full_name: 'BENJAMIN TEO',
      marital_status: 'Married',
      mobile_number: '+65 8765 1234',
      email: 'b.teo@biz.com',
      address: {
        address_line1: 'BLK 700 JURONG WEST',
        address_line2: '#07-07',
        postal_code: '640700',
      },
    },
    maid_info: {
      id: 'M0555-55T',
      name: 'VIKRAMA DEVI',
      date_of_birth: '1995-01-01',
      gender: 'Female',
      phone_number: '98765432',
      nationality: 'INDIA',
      passport_number: null,
      forgeign_id_number: null,
    },
    policy_no: 'GMA24F0071121',
  },
  {
    // "policy_type": "MOTOR POLICY - PRIVATE",
    policy_type: 'car',
    policy_type_name: 'motor vehicle - car',
    start_date: '2025-05-15',
    end_date: '2026-05-14',
    issue_date: '2025-05-10',
    plan_type: 'Comprehensive - Standard',
    scheme: 'Authorized Workshop',
    intermediary_name: 'MSIG INSURANCE (SINGAPORE) PTE. LTD.',
    premium: 1100.0,
    policy_status: 'pending',
    tags: 'new application',
    policy_holder: {
      full_name: 'WAN CHING',
      marital_status: 'Married',
      mobile_number: '+65 9010 2030',
      email: 'w.ching@corp.sg',
      address: {
        address_line1: '15 PASIR RIS GROVE',
        address_line2: null,
        postal_code: '518341',
      },
    },
    drivers: [],
    vehicle: {
      registration_number: 'SJW2000R',
      chassis_number: 'JM1FNH35A4U765432',
      capacity: '1499 CC',
      vehicle_usage: 'MOTOR PRIVATE CAR',
      make_model: 'KIA CERATO 1.6',
      engine_number: '4019811E',
      registration_year: 22023,
      hire_purchase_company: 'UOB',
      registration_no: 'SJW2000R',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: 100.0,
        standard_excess: 1000.0,
        standard_excess_outside_sg: 1000.0,
      },
      additional_excess: {
        unnamed_drivers: 500.0,
        young_or_inexperienced: 3000.0,
      },
    },
    policy_no: 'MC2025013',
  },
  {
    // "policy_type": "MOTOR POLICY - MOTORCYCLE",
    policy_type: 'motorcycle',
    policy_type_name: 'motor vehicle - motorcycle',
    start_date: '2025-01-08',
    end_date: '2026-01-07',
    issue_date: '2025-01-05',
    plan_type: 'Third Party Only',
    scheme: 'Direct Sales',
    intermediary_name: null,
    premium: 220.0,
    policy_status: 'active',
    tags: null,
    policy_holder: {
      full_name: 'AHMAD BIN SAMAD',
      marital_status: 'Single',
      mobile_number: '+65 8900 1200',
      email: 'ahmad.samad@mail.co',
      address: {
        address_line1: 'BLK 99 JALAN BAHAR',
        address_line2: '#01-01',
        postal_code: '699999',
      },
    },
    drivers: [],
    vehicle: {
      registration_number: 'FBL1122C',
      chassis_number: 'JM1FDH53A4U000002',
      capacity: '150 CC',
      vehicle_usage: 'MOTOR MOTORCYCLE',
      make_model: 'YAMAHA YZF-R15',
      engine_number: '1N9876544',
      registration_year: 2024,
      hire_purchase_company: 'N/A',
      registration_no: 'FBL1122C',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: null,
        standard_excess: 500.0,
        standard_excess_outside_sg: 500.0,
      },
      additional_excess: {
        unnamed_drivers: 300.0,
        young_or_inexperienced: 2000.0,
      },
    },
    policy_no: 'MC2025014',
  },
  {
    // "policy_type": "DUPLICATE POLICY - MOTORCYCLE",
    policy_type: 'motorcycle',
    policy_type_name: 'motor vehicle - motorcycle',
    start_date: '2024-09-20',
    end_date: '2025-09-19',
    issue_date: '2024-09-15',
    plan_type: 'Third Party Only',
    scheme: 'Direct Sales',
    intermediary_name: null,
    premium: 250.0,
    policy_status: 'active',
    tags: null,
    policy_holder: {
      full_name: 'PETER NG',
      marital_status: 'Married',
      mobile_number: '+65 9765 4321',
      email: 'peter.ng@home.sg',
      address: {
        address_line1: 'BLK 500 YISHUN AVENUE 11',
        address_line2: '#03-100',
        postal_code: '760500',
      },
    },
    drivers: [],
    vehicle: {
      registration_number: 'FBM5432B',
      chassis_number: 'JM1FDH53A4U000001',
      capacity: '500 CC',
      vehicle_usage: 'MOTOR MOTORCYCLE',
      make_model: 'HONDA CB500X',
      engine_number: '1N9876543',
      registration_year: 2021,
      hire_purchase_company: 'N/A',
      registration_no: 'FBM5432B',
    },
    excess: {
      policy_excess: {
        windscreen_sun_moon_roof: null,
        standard_excess: 500.0,
        standard_excess_outside_sg: 500.0,
      },
      additional_excess: {
        unnamed_drivers: 300.0,
        young_or_inexperienced: 2000.0,
      },
    },
    policy_no: 'MC2024009_829',
  },
];

const getPolicy = (payload: any) => {
  const results = MOCK_DATA.map((item, idx) => ({
    id: idx + 1,
    ...item,
  })).filter((item) => {
    if (payload.policyNo) return item.policy_no === payload.policyNo;

    const queryStr = payload.queryStr?.toLowerCase() ?? '';
    return (
      (!payload.policyStatus || payload.policyStatus === item.policy_status) &&
      (!payload.tags || payload.tags.split(',').includes(item.tags)) &&
      (!payload.policyType ||
        payload.policyType === 'all' ||
        payload.policyType === item.policy_type) &&
      (!payload.queryStr ||
        item.policy_no?.toLowerCase()?.startsWith(queryStr) ||
        item.policy_type_name?.startsWith(queryStr) ||
        item.vehicle?.registration_no?.toLowerCase()?.startsWith(queryStr) ||
        item.maid_info?.name?.toLowerCase()?.startsWith(queryStr))
    );
  });

  const summary = {
    total: MOCK_DATA.length,
    active: MOCK_DATA.filter((item) => item.policy_status === 'active').length,
    pending_renewal: MOCK_DATA.filter((item) => item.tags === 'pending_renewal')
      .length,
    expired: MOCK_DATA.filter((item) => item.policy_status === 'expired')
      .length,
    cancelled: MOCK_DATA.filter((item) => item.tags === 'cancelled').length,
  };

  if (!payload.pageNo || !payload.pageSize) return { summary, results };
  const fromIdx = (payload.pageNo - 1) * payload.pageSize;
  const toIdx = fromIdx + payload.pageSize;

  return { summary, results: results.slice(fromIdx, toIdx) };
};

let timeout: any;

// eslint-disable-next-line import/no-anonymous-default-export
export default {
  getPolicies<T = PolicyResponse>(
    payload: PolicyPayload,
  ): Promise<AxiosResponse<T>> {
    const params = {
      policyNo: payload?.policyNo ?? undefined,
      queryStr: payload?.queryStr,
      status: payload?.policyStatus,
      type: payload?.policyType,
      tags: payload?.tags,
      pagination: {
        page: payload.pageNo,
        pageSize: payload.pageSize,
      },
    };

    clearTimeout(timeout);
    // return baseClient.get<T>(`${API_POLICY_GET}`, { params });
    return new Promise((resolve) => {
      timeout = setTimeout(
        () => {
          return resolve({
            data: {
              data: getPolicy(payload),
              meta: { pagination: {} },
            },
          });
        },
        Math.ceil(Math.random() * 100 + 50),
      );
    });
  },
};
