name: Check build

on:
  push:
    branches: 
        - main
        - development
  pull_request: {}

jobs:
  build:
    name: 🚀 Build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://neondb_owner:npg_MJa3rWqG4LRK@ep-steep-resonance-a10i3eec-pooler.ap-southeast-1.aws.neon.tech/ecics_dev?sslmode=require&schema=public
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: 📥 Download deps
        run: npm install --frozen-lockfile

      - name: Build project
        run: npm run build --if-present